version: '3.9'

services:

  tunnel:
    image: cloudflare/cloudflared:2021.8.2
    restart: unless-stopped
    # run docker-compose up -d with the first command to create a tunnel first; ignore errors since this a "hacky" way of doing this.
    # once that's done, comment out the command: tunnel create cloudflared and uncomment the 2nd command;
    # to get the certificate (if you don't have your own yet), login to your Cloudflare account FIRST, then go to https://dash.cloudflare.com/warp
    # select a domain you prefer but it doesn't matter since this cert.pem file is valid account wide, then download it
    # create a cloudflared folder in the project root directory and move the certificate inside the cloudflared folder
    # after you run docker-compose up -d, it will generate a [UUID].json file inside the cloudflared folder. copy the [UUID] and replace the [UUID] inside the config.yml file
    # go back to your Cloudflare dashboard and create a new CNAME DNS record with Name: [Your-Subdomain] Content:[UUID].cfargotunnel.com
    # to add sites, modify the Ingress in the config.yml file
    # if everything is done right, then it should work.
    command: tunnel create cloudflared
    # command: tunnel run cloudflared
    ports:
    # you may chose your own ports, I just chose these
    - 5054:5054
    volumes:
      - ./cloudflared:/etc/cloudflared
